import "./globals.css";

export const metadata = {
  description: "Generated by create next app",
  title: "Glocal",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" data-theme="fantasy">
      <body className="mx-auto w-full max-w-lg">{children}</body>
    </html>
  );
}
